version: "3.9"
services:
  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
  redis:
    image: redis:7
    container_name: epty-redis
    ports:
      - "6379:6379"
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/eptydb
      - REDIS_HOST=redis
      - REDIS_PORT:6379

    depends_on:
      - mongo

  mongo:
    image: mongo:6
    container_name: epty-mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
